import {
  Employee,
  CompanyRecord,
  BranchRecord,
  DepartmentRecord,
  TeamRecord,
  AttendanceRecord,
  LeaveRequestRecord,
  ProjectRecord,
  TimesheetRecord,
  PayrollRecord,
} from "./types";

export const initialCompanies: CompanyRecord[] = [
  {
    id: "digisail-company-1",
    name: "DigiSail Global Inc.",
    legalName: "DigiSail Technologies, Inc.",
    subdomain: "digisail",
    plan: "ENTERPRISE",
    currency: "USD",
    timezone: "America/New_York",
    adminName: "Sarah Jenkins",
    adminEmail: "sarah.jenkins@digisail.com",
    branchCount: 2,
    employeeCount: 70,
    status: "ACTIVE",
    maxSeats: 9999,
    maxBranches: 999,
    monthlyPrice: 1999,
    seatUtilizationPct: 70,
    renewalDate: "2026-11-01",
    createdAt: "2026-01-15",
  },
  {
    id: "company-2",
    name: "Apex Financial Partners",
    legalName: "Apex Global Wealth LLC",
    subdomain: "apexfin",
    plan: "GROWTH",
    currency: "USD",
    timezone: "America/Chicago",
    adminName: "Marcus Vance",
    adminEmail: "marcus.v@apexfin.com",
    branchCount: 1,
    employeeCount: 25,
    status: "ACTIVE",
    maxSeats: 100,
    maxBranches: 10,
    monthlyPrice: 799,
    seatUtilizationPct: 25,
    renewalDate: "2026-10-28",
    createdAt: "2026-04-10",
  },
  {
    id: "company-3",
    name: "Nordic Logistics Co.",
    legalName: "Nordic Freight & Logistics AB",
    subdomain: "nordic",
    plan: "STARTER",
    currency: "EUR",
    timezone: "Europe/Stockholm",
    adminName: "Astrid Lind",
    adminEmail: "astrid@nordiclogistics.se",
    branchCount: 1,
    employeeCount: 14,
    status: "TRIAL",
    maxSeats: 25,
    maxBranches: 2,
    monthlyPrice: 299,
    seatUtilizationPct: 56,
    renewalDate: "2026-10-15",
    createdAt: "2026-09-01",
  },
];

export const initialBranches: BranchRecord[] = [
  {
    id: "branch-1",
    companyId: "digisail-company-1",
    companyName: "DigiSail Global Inc.",
    name: "New York Headquarters",
    code: "HQ-NYC",
    city: "New York",
    country: "United States",
    adminName: "Michael Scott",
    departmentCount: 3,
    employeeCount: 42,
  },
  {
    id: "branch-2",
    companyId: "digisail-company-1",
    companyName: "DigiSail Global Inc.",
    name: "London Technology Hub",
    code: "HUB-LON",
    city: "London",
    country: "United Kingdom",
    adminName: "Emma Watson",
    departmentCount: 2,
    employeeCount: 28,
  },
  {
    id: "branch-3",
    companyId: "company-2",
    companyName: "Apex Financial Partners",
    name: "Chicago Trading Floor",
    code: "APEX-CHI",
    city: "Chicago",
    country: "United States",
    adminName: "Marcus Vance",
    departmentCount: 1,
    employeeCount: 25,
  },
  {
    id: "branch-4",
    companyId: "company-3",
    companyName: "Nordic Logistics Co.",
    name: "Stockholm Harbor Hub",
    code: "NORDIC-STO",
    city: "Stockholm",
    country: "Sweden",
    adminName: "Astrid Lind",
    departmentCount: 1,
    employeeCount: 14,
  },
];

export const initialDepartmentsList: DepartmentRecord[] = [
  {
    id: "dept-1",
    name: "Engineering",
    code: "ENG",
    branchId: "branch-1",
    branchName: "New York Headquarters",
    adminName: "Alex Chen",
    teamCount: 3,
    employeeCount: 24,
  },
  {
    id: "dept-2",
    name: "Product Design",
    code: "DESIGN",
    branchId: "branch-1",
    branchName: "New York Headquarters",
    adminName: "Elena Rostova",
    teamCount: 2,
    employeeCount: 8,
  },
  {
    id: "dept-3",
    name: "People & Culture",
    code: "HR",
    branchId: "branch-1",
    branchName: "New York Headquarters",
    adminName: "Sarah Jenkins",
    teamCount: 1,
    employeeCount: 5,
  },
];

export const initialTeamsList: TeamRecord[] = [
  {
    id: "team-1",
    name: "Core Platform & Cloud Team",
    code: "ENG-CORE",
    departmentId: "dept-1",
    departmentName: "Engineering",
    leadName: "David Miller",
    memberCount: 8,
  },
  {
    id: "team-2",
    name: "Frontend & Mobile Experience",
    code: "ENG-FE",
    departmentId: "dept-1",
    departmentName: "Engineering",
    leadName: "Priya Patel",
    memberCount: 7,
  },
  {
    id: "team-3",
    name: "Enterprise Design Systems",
    code: "DS-SYS",
    departmentId: "dept-2",
    departmentName: "Product Design",
    leadName: "Elena Rostova",
    memberCount: 5,
  },
];

export const initialEmployees: Employee[] = [
  {
    id: "emp-1",
    employeeNumber: "DS-001",
    firstName: "Sarah",
    lastName: "Jenkins",
    email: "sarah.jenkins@digisail.com",
    phone: "+1 (555) 234-5678",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "People & Culture",
    designation: "Head of People & Culture",
    hireDate: "2021-03-15",
    employmentType: "FULL_TIME",
    status: "ACTIVE",
    onboardingStatus: "ACTIVE",
    baseSalary: 110000,
    currency: "USD",
    location: "New York, USA",
  },
  {
    id: "emp-2",
    employeeNumber: "DS-002",
    firstName: "Alexander",
    lastName: "Chen",
    email: "alex.chen@digisail.com",
    phone: "+1 (555) 345-6789",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    team: "Core Platform & Cloud Team",
    designation: "Principal Architect & Dept Head",
    hireDate: "2020-01-10",
    employmentType: "FULL_TIME",
    status: "ACTIVE",
    onboardingStatus: "ACTIVE",
    baseSalary: 145000,
    currency: "USD",
    location: "New York, USA",
  },
  {
    id: "emp-3",
    employeeNumber: "DS-003",
    firstName: "David",
    lastName: "Miller",
    email: "david.miller@digisail.com",
    phone: "+1 (555) 444-5566",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    team: "Core Platform & Cloud Team",
    designation: "Team Lead - Cloud Systems",
    managerName: "Alexander Chen",
    hireDate: "2022-04-12",
    employmentType: "FULL_TIME",
    status: "ACTIVE",
    onboardingStatus: "ACTIVE",
    baseSalary: 125000,
    currency: "USD",
    location: "New York, USA",
  },
  {
    id: "emp-4",
    employeeNumber: "DS-004",
    firstName: "Priya",
    lastName: "Patel",
    email: "priya.patel@digisail.com",
    phone: "+1 (555) 678-9012",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    team: "Core Platform & Cloud Team",
    designation: "Senior Fullstack Engineer",
    managerName: "David Miller",
    hireDate: "2023-02-14",
    employmentType: "FULL_TIME",
    status: "ACTIVE",
    onboardingStatus: "ACTIVE",
    baseSalary: 98000,
    currency: "USD",
    location: "Austin, USA",
  },
  // Candidate in Stage 1 Review (Awaiting Dept Admin Alex Chen)
  {
    id: "emp-5",
    employeeNumber: "DS-006",
    firstName: "Liam",
    lastName: "O'Connor",
    email: "liam.oc@digisail.com",
    phone: "+1 (555) 789-0123",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    team: "Core Platform & Cloud Team",
    designation: "Distributed Backend Specialist",
    createdByName: "David Miller (Team Lead)",
    hireDate: "2026-10-01",
    employmentType: "FULL_TIME",
    status: "PROBATION",
    onboardingStatus: "PENDING_DEPT_APPROVAL",
    baseSalary: 105000,
    currency: "USD",
    location: "Remote",
    approvalHistory: [],
  },
  // Candidate in Stage 2 Review (Approved by Dept Admin Alex Chen, Awaiting Branch Admin Michael Scott)
  {
    id: "emp-6",
    employeeNumber: "DS-007",
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.m@digisail.com",
    phone: "+1 (555) 998-1122",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    team: "Core Platform & Cloud Team",
    designation: "DevOps & Infrastructure Lead",
    createdByName: "David Miller (Team Lead)",
    hireDate: "2026-10-01",
    employmentType: "FULL_TIME",
    status: "PROBATION",
    onboardingStatus: "PENDING_BRANCH_APPROVAL",
    baseSalary: 112000,
    currency: "USD",
    location: "New York HQ",
    approvalHistory: [
      {
        id: "app-1",
        stage: "DEPARTMENT_REVIEW",
        action: "APPROVE",
        reviewerName: "Alex Chen",
        reviewerRole: "Department Admin (Engineering)",
        comments: "Candidate passed deep architecture review with distinction. Ready for final Branch HR sign-off.",
        date: "2026-10-04 14:30",
      },
    ],
  },
];

export const initialAttendances: AttendanceRecord[] = [
  {
    id: "att-1",
    employeeId: "emp-1",
    employeeName: "Sarah Jenkins",
    employeeAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "People & Culture",
    date: "2026-10-05",
    punchIn: "08:45 AM",
    punchOut: undefined,
    workHours: 7.5,
    status: "PRESENT",
    ipAddress: "192.168.1.42",
  },
  {
    id: "att-2",
    employeeId: "emp-2",
    employeeName: "Alexander Chen",
    employeeAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    date: "2026-10-05",
    punchIn: "09:02 AM",
    punchOut: undefined,
    workHours: 7.2,
    status: "PRESENT",
    ipAddress: "192.168.1.18",
  },
  {
    id: "att-3",
    employeeId: "emp-3",
    employeeName: "David Miller",
    employeeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    date: "2026-10-05",
    punchIn: "08:30 AM",
    punchOut: undefined,
    workHours: 7.8,
    status: "PRESENT",
    ipAddress: "192.168.1.101",
  },
  {
    id: "att-4",
    employeeId: "emp-4",
    employeeName: "Priya Patel",
    employeeAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    branch: "New York Headquarters",
    department: "Engineering",
    date: "2026-10-05",
    punchIn: "08:55 AM",
    punchOut: undefined,
    workHours: 7.3,
    status: "PRESENT",
    ipAddress: "192.168.1.55",
  },
];

export const initialLeaveRequests: LeaveRequestRecord[] = [
  {
    id: "leave-1",
    employeeId: "emp-4",
    employeeName: "Priya Patel",
    employeeAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    department: "Engineering",
    leaveType: "Medical / Sick Leave",
    leaveTypeCode: "SICK",
    colorHex: "#ef4444",
    startDate: "2026-10-10",
    endDate: "2026-10-11",
    totalDays: 2,
    reason: "Scheduled dental surgery & recovery",
    status: "PENDING",
    appliedAt: "2026-10-04",
  },
];

export const initialProjects: ProjectRecord[] = [
  {
    id: "proj-1",
    name: "DigiSail Cloud Platform v4",
    code: "DSP-CLOUD",
    client: "Internal SaaS Core",
    status: "ACTIVE",
    budget: 250000,
    hoursSpent: 1240,
    totalHours: 1600,
    teamCount: 8,
    deadline: "2026-12-15",
  },
  {
    id: "proj-2",
    name: "FinTech Enterprise Integration",
    code: "FIN-INT",
    client: "Apex Financial Partners",
    status: "ACTIVE",
    budget: 180000,
    hoursSpent: 620,
    totalHours: 900,
    teamCount: 5,
    deadline: "2026-11-30",
  },
];

export const initialTimesheets: TimesheetRecord[] = [
  {
    id: "ts-1",
    employeeName: "Priya Patel",
    projectName: "DigiSail Cloud Platform v4",
    date: "2026-10-04",
    hoursWorked: 8,
    taskDescription: "Engineered branch and department level tenancy isolation filters",
    status: "APPROVED",
  },
];

export const initialPayroll: PayrollRecord[] = [
  {
    id: "pay-1",
    employeeName: "Sarah Jenkins",
    employeeNumber: "DS-001",
    department: "People & Culture",
    designation: "Head of People & Culture",
    month: "September",
    year: 2026,
    basicSalary: 9166.67,
    allowances: 800,
    deductions: 500,
    tax: 1980,
    netSalary: 7486.67,
    status: "PAID",
    paymentDate: "2026-09-30",
  },
  {
    id: "pay-2",
    employeeName: "Alexander Chen",
    employeeNumber: "DS-002",
    department: "Engineering",
    designation: "Principal Architect",
    month: "September",
    year: 2026,
    basicSalary: 12083.33,
    allowances: 1000,
    deductions: 600,
    tax: 2750,
    netSalary: 9733.33,
    status: "PAID",
    paymentDate: "2026-09-30",
  },
];
